# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choiceTxt',
            field=models.CharField(default='Yes', max_length=50),
        ),
    ]
